# Numpy

In [2]:
import numpy as np

In [90]:
np_arr = np.array([2, 4, 6, 8, 16])
np_arr

array([ 2,  4,  6,  8, 16])

In [91]:
np_arr = np_arr * 2
np_arr

array([ 4,  8, 12, 16, 32])

In [92]:
np_arr = np_arr ** 2 #likewise for all math equations
np_arr

array([  16,   64,  144,  256, 1024])

In [93]:
ls = [1, 2, 3, 4, 5, 6]
ls

[1, 2, 3, 4, 5, 6]

In [94]:
np_ls = np.array(ls)
np_ls

array([1, 2, 3, 4, 5, 6])

In [95]:
np_ls * 2

array([ 2,  4,  6,  8, 10, 12])

In [96]:
ls * 2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [97]:
np_ls[0]

1

In [98]:
np_ls[0:3]

array([1, 2, 3])

In [99]:
np_ls[0:5:2] 

array([1, 3, 5])

In [100]:
np_ls.shape #this is one dimensional array

(6,)

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.arange(10, 100)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [8]:
arr = np.arange(10.0)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
arr = np.arange(10.0, 100.0)
arr

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61.,
       62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74.,
       75., 76., 77., 78., 79., 80., 81., 82., 83., 84., 85., 86., 87.,
       88., 89., 90., 91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [12]:
arr = np.arange(-5, 15)
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14])

In [13]:
arr = np.arange(0, 100, 5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [42]:
x = np.arange(6)
print(x)
x = x.reshape((2, 3))
x

[0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [16]:
np.zeros((2, 1)) #two dimensional array

array([[0.],
       [0.]])

In [17]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [20]:
print(x) #from above

[[0 1 2]
 [3 4 5]]


In [21]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
y = np.arange(3, dtype=float)
y

array([0., 1., 2.])

In [23]:
np.zeros_like(y)

array([0., 0., 0.])

In [43]:
np.full((2, 4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [45]:
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])

In [27]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
np.full_like(x, 1)

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
np.full_like(x, 0.1) #it gives 0 because, x have type int not float

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
np.full_like(x, 0.1, dtype=float)

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [37]:
y = np.zeros([2, 2, 3], dtype=int) #3 dimensional
np.full_like(y, [0, 0, 255])

array([[[  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255]]])

## For 2 and 2+ dimensional numpy arrays

In [38]:
np.array([1, 2, 3], ndmin=2) #by ndmin, min dimension can give to array, like here the array is one dimensional but by 'ndmin=2' this will create 2d array

array([[1, 2, 3]])

In [108]:
np_arr2 = np.array([[2, 3, 4, 5, 2, 5, 7, 8], [4, 5, 7, 5, 2, 5, 7, 8]])
np_arr2

array([[2, 3, 4, 5, 2, 5, 7, 8],
       [4, 5, 7, 5, 2, 5, 7, 8]])

In [109]:
np_arr2.shape #2d array (hint: row, column)

(2, 8)

In [110]:
np_arr2 = np_arr2 * 2
np_arr2

array([[ 4,  6,  8, 10,  4, 10, 14, 16],
       [ 8, 10, 14, 10,  4, 10, 14, 16]])

In [111]:
np_arr2 = np_arr2 ** 2 #likewise for all math equations
np_arr2

array([[ 16,  36,  64, 100,  16, 100, 196, 256],
       [ 64, 100, 196, 100,  16, 100, 196, 256]])

In [36]:
np_arr2[0]

array([2, 3, 4, 5, 2, 5, 7, 8])

In [37]:
np_arr2[0][0] #[0, 0] will also give same result

2

In [38]:
np_arr2[0][1:2] #[0, 1:2] will also give same result

array([3])

In [40]:
np_arr2[0][::2] #[0, ::2] will also give same result

array([2, 4, 2, 7])

In [123]:
np_arr3 = np.array([
                    [[2, 3, 4, 5, 2, 5, 7, 8], 
                     [4, 5, 7, 5, 2, 5, 7, 8],
                    [4, 5, 7, 5, 2, 5, 7, 8]], 
    
                    [[2, 3, 4, 5, 2, 5, 7, 8], 
                     [4, 5, 7, 5, 2, 5, 7, 8],
                    [4, 5, 7, 5, 2, 5, 7, 8]]
                   ])
np_arr3

array([[[2, 3, 4, 5, 2, 5, 7, 8],
        [4, 5, 7, 5, 2, 5, 7, 8],
        [4, 5, 7, 5, 2, 5, 7, 8]],

       [[2, 3, 4, 5, 2, 5, 7, 8],
        [4, 5, 7, 5, 2, 5, 7, 8],
        [4, 5, 7, 5, 2, 5, 7, 8]]])

In [124]:
np_arr3.shape

(2, 3, 8)

In [131]:
np_arr3 = np_arr2 * 2
np_arr3

array([[[ 32,  72, 128, 200,  32, 200, 392, 512],
        [128, 200, 392, 200,  32, 200, 392, 512]],

       [[ 32,  72, 128, 200,  32, 200, 392, 512],
        [128, 200, 392, 200,  32, 200, 392, 512]]])

In [132]:
np_arr3 = np_arr2 ** 2 #likewise for all math equations
np_arr3

array([[[  256,  1296,  4096, 10000,   256, 10000, 38416, 65536],
        [ 4096, 10000, 38416, 10000,   256, 10000, 38416, 65536]],

       [[  256,  1296,  4096, 10000,   256, 10000, 38416, 65536],
        [ 4096, 10000, 38416, 10000,   256, 10000, 38416, 65536]]])

In [133]:
np_arr3[0]

array([[  256,  1296,  4096, 10000,   256, 10000, 38416, 65536],
       [ 4096, 10000, 38416, 10000,   256, 10000, 38416, 65536]])

In [134]:
np_arr3[0][0] #[0, 0] will also give same result

array([  256,  1296,  4096, 10000,   256, 10000, 38416, 65536])

In [140]:
np_arr3[0][0][1] #[0, 0, 1] will also give same result

1296

In [143]:
np_arr3[0][1:] #[0, 1:] will also give same result 

array([[ 4096, 10000, 38416, 10000,   256, 10000, 38416, 65536]])

In [154]:
np_arr3[0][1:][0] #1d

array([ 4096, 10000, 38416, 10000,   256, 10000, 38416, 65536])

In [155]:
np_arr3[0][1:][0][0]

4096

In [158]:
np_arr3[0][::2][0] 

array([  256,  1296,  4096, 10000,   256, 10000, 38416, 65536])

In [159]:
np_arr3[0][::2][0][1::2] 

array([ 1296, 10000, 10000, 65536])